---
# @see https://zohaib.me/managing-secrets-in-nixos-home-manager-with-sops/
keys:
  - &workstation age1kpn9v4jyjf85779a64hh3qrfk6sd6nwzxprs5ezkdkes9x2vxvcqgzklgr
  - &host_framework13 age10vwddsxes35azh349ffejrrzcj6wmnz56z5gqzgd764u2j6kw4ls3c8gz0
  - &host_ser6 age1j5qe7lrhcrqyvj4u5n8rzqxy74vn099m6m00qunjvhdfs37zkquq3cp0e4
  - &user_ctorgalson age1z6uaq4854etlrar3pf5a97xkx3nrurdmus09eq5cxz33t5q6r35qwluzlu
  # ~/.config/sops/age/keys.txt
  # - &host_executive14 age1kpn9v4jyjf85779a64hh3qrfk6sd6nwzxprs5ezkdkes9x2vxvcqgzklgr
  # - &host_framework13 age1kpn9v4jyjf85779a64hh3qrfk6sd6nwzxprs5ezkdkes9x2vxvcqgzklgr
  # - &host_ser6 age1kpn9v4jyjf85779a64hh3qrfk6sd6nwzxprs5ezkdkes9x2vxvcqgzklgr

creation_rules:
  - path_regex: workstation/(shared|framework13|ser6).yaml$
    key_groups:
      - age:
        - *host_framework13
        - *host_ser6
        - *user_ctorgalson
        - *workstation
        # - *host_executive14

  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *host_framework13
          - *host_ser6
          - *user_ctorgalson
          - *workstation
          # - *host_executive14
