#!/usr/bin/env bash

# Id from BWS.
id="c34b225f-0c4e-42d6-8c2c-b28d0133105f"
filepath="$HOME/.config/sops/age/keys.txt"

# Request a BWS access token.
echo -n "BWS_ACCESS_TOKEN: "
read -rs bws_access_token

# Ensure the directory exists.
mkdir -p "$(dirname "$filepath")"

# Retrieve the secret.
secret=$(BWS_ACCESS_TOKEN="$bws_access_token" bws secret get "$id")

# Dump the contents of the secret into a file, and set the file's permissions.
jq --raw-output .value <<< "$secret" > "$filepath"
chmod "644" "$filepath"
