# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2f2055db-4f9f-44e9-a2b0-2b8cba6b8c4d";
      fsType = "ext4";
    };
  fileSystems."/home/ctorgalson/Storage" =
    { device = "/dev/disk/by-uuid/7eae0fe0-d1c8-4b4b-90f1-d8c587253109";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-dc346729-efd3-433c-86d3-599eec6b84d3".device = "/dev/disk/by-uuid/dc346729-efd3-433c-86d3-599eec6b84d3";
  boot.initrd.luks.devices."luks-91eef538-61b2-46c9-8f21-c9d4ea615b31".device = "/dev/disk/by-uuid/91eef538-61b2-46c9-8f21-c9d4ea615b31";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/39E9-5BAB";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0e0b39df-e87d-4e4d-9a59-2373bad81224"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
