---
# Creates default directories and symlinks in user home directory.
#
# Note that this is a first go and assumes the requisite directories 
- name: "Create default directories and links."
  hosts: "localhost"
  connection: "local"
  vars:
    owner: "ctorgalson"
    group: "users"
    home_path: "/home/ctorgalson"
    mount_path: "/run/media/ctorgalson/Storage"
    directories:
      - "{{ home_path }}/Dev/AT"
      - "{{ home_path }}/Dev/BH"
      - "{{ mount_path }}/Documents"
      - "{{ mount_path }}/Music"
      - "{{ mount_path }}/Nextcloud"
      - "{{ mount_path }}/Videos"
    links:
      - src: "{{ mount_path }}/Documents"
        dest: "{{ home_path }}/Documents"
      - src: "{{ mount_path }}/Music"
        dest: "{{ home_path }}/Music"
      - src: "{{ mount_path }}/Nextcloud"
        dest: "{{ home_path }}/Nextcloud"
      - src: "{{ mount_path }}/Nextcloud"
        dest: "{{ home_path }}/Shared"
      - src: "{{ mount_path }}/Videos"
        dest: "{{ home_path }}/Videos"
  tasks:
    - name: "Create home directories."
      file:
        path: "{{ home_dir }}"
        state: "directory"
      loop: "{{ directories }}"
      loop_control:
        loop_var: "home_dir"

    - name: "Create mount directories."
      file:
        path: "{{ mount_dir.src }}"
        state: "directory"
      loop: "{{ links }}"
      loop_control:
        loop_var: "mount_dir"

    - name: "Create default symlinks."
      file:
        src: "{{ link.src }}"
        dest: "{{ link.dest }}"
        state: "link"
      loop: "{{ links }}"
      loop_control:
        loop_var: "link"
